version: '3'

services:
  web:
    image: xed_web:v1
    container_name: xed_web
    build: 
      context: ./app
      dockerfile: Dockerfile

    environment:
      # To reload app on windows
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    restart: always

    env_file: .env

    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/node_modules:/app/node_modules

    ports:
      - 3000:3000
