import './globals.css'
import type { Metadata } from 'next'
import AppRegistry from './AppRegistry'

export const metadata: Metadata = {
  title: 'Xed',
  description: 'Generated by create next app',
}

export default ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang='en'>
    <body>
      <AppRegistry>{children}</AppRegistry>
    </body>
  </html>
)
