import './globals.css'
import type { Metadata } from 'next'
import ThemeRegistry from './ThemeRegistry'

export const metadata: Metadata = {
  title: 'Xed',
  description: 'Generated by create next app',
}

export default ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body>
      <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
    </body>
  </html>
)
